format_version: "v1"
environment:
  game_version: "1.17.1"
  server_core: "fabric"
  server_core_version: "0.14.24"
  modding_platform: "fabric"
  modding_platform_version: "0.14.24"
  mcdr: true
packages:
  - id: fabric/carpet
    version: "1.4.57"
    source: modrinth
    role: required
    side: server
  - id: fabric/fabric-api
    version: "0.46.1+1.17"
    source: modrinth
    role: required
    side: server
