package mcdr

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/stratummc/stratum/internal/agent/process"
)

const configYMLName = "config.yml"

type RuntimeConfig struct {
	ServerWorkDir  string
	ServerJarName  string
	JavaExecutable string
	PluginDir      string
	LogDir         string
	ConfigDir      string
}

func NewRuntimeConfig(layout process.MCDRRuntimeLayout) RuntimeConfig {
	return RuntimeConfig{
		ServerWorkDir: layout.MCDRServerDir,
		PluginDir:     layout.MCDRPluginsDir,
		LogDir:        layout.MCDRLogsDir,
		ConfigDir:     layout.MCDRConfigDir,
	}
}

func WriteRuntimeConfig(layout process.MCDRRuntimeLayout, cfg RuntimeConfig) (string, error) {
	if cfg == (RuntimeConfig{}) {
		cfg = NewRuntimeConfig(layout)
	}
	if err := validateRuntimeConfig(layout, cfg); err != nil {
		return "", err
	}
	configPath := filepath.Join(layout.MCDRConfigDir, configYMLName)
	if !filesystemPathWithin(layout.SessionLayout.SessionRoot, configPath) || !filesystemPathWithin(layout.MCDRConfigDir, configPath) {
		return "", errors.New("MCDR config.yml path escapes runtime layout")
	}
	if err := os.MkdirAll(layout.MCDRConfigDir, 0o750); err != nil {
		return "", fmt.Errorf("create MCDR config directory: %w", err)
	}
	payload := renderRuntimeConfig(cfg)
	tmp, err := os.CreateTemp(layout.MCDRConfigDir, ".config-yml-*.tmp")
	if err != nil {
		return "", fmt.Errorf("create temporary MCDR config.yml: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(0o640); err != nil {
		_ = tmp.Close()
		return "", fmt.Errorf("set MCDR config.yml permissions: %w", err)
	}
	if _, err := tmp.Write(payload); err != nil {
		_ = tmp.Close()
		return "", fmt.Errorf("write MCDR config.yml: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return "", fmt.Errorf("sync MCDR config.yml: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return "", fmt.Errorf("close MCDR config.yml: %w", err)
	}
	if err := os.Rename(tmpPath, configPath); err != nil {
		return "", fmt.Errorf("replace MCDR config.yml: %w", err)
	}
	return configPath, nil
}

func validateRuntimeConfig(layout process.MCDRRuntimeLayout, cfg RuntimeConfig) error {
	checks := []struct {
		name     string
		value    string
		expected string
	}{
		{name: "server_work_dir", value: cfg.ServerWorkDir, expected: layout.MCDRServerDir},
		{name: "plugin_dir", value: cfg.PluginDir, expected: layout.MCDRPluginsDir},
		{name: "log_dir", value: cfg.LogDir, expected: layout.MCDRLogsDir},
		{name: "config_dir", value: cfg.ConfigDir, expected: layout.MCDRConfigDir},
	}
	for _, check := range checks {
		if check.value != check.expected {
			return fmt.Errorf("%s must come from Agent MCDR runtime layout", check.name)
		}
		if !filesystemPathWithin(layout.SessionLayout.SessionRoot, check.value) || !filesystemPathWithin(layout.MCDRRoot, check.value) {
			return fmt.Errorf("%s escapes MCDR runtime layout", check.name)
		}
	}
	return nil
}

func renderRuntimeConfig(cfg RuntimeConfig) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by Stratum Agent. Do not store credentials here.\n")
	b.WriteString("working_directory: ")
	b.WriteString(quoteYAMLString(cfg.ServerWorkDir))
	b.WriteByte('\n')
	b.WriteString("plugin_directories:\n")
	b.WriteString("  - ")
	b.WriteString(quoteYAMLString(cfg.PluginDir))
	b.WriteByte('\n')
	b.WriteString("handler:\n")
	b.WriteString("  type: vanilla_handler\n")
	b.WriteString("logging:\n")
	b.WriteString("  file: ")
	b.WriteString(quoteYAMLString(filepath.Join(cfg.LogDir, "mcdr.log")))
	b.WriteByte('\n')
	b.WriteString("config_directory: ")
	b.WriteString(quoteYAMLString(cfg.ConfigDir))
	b.WriteByte('\n')
	if cfg.ServerJarName != "" {
		javaCmd := cfg.JavaExecutable
		if javaCmd == "" {
			javaCmd = "java"
		}
		b.WriteString("start_command: ")
		b.WriteString(quoteYAMLString(javaCmd))
		b.WriteString(" -jar ")
		b.WriteString(quoteYAMLString(cfg.ServerJarName))
		b.WriteString(" nogui\n")
	}
	return b.Bytes()
}

func quoteYAMLString(value string) string {
	value = strings.ReplaceAll(value, `\`, `/`)
	value = strings.ReplaceAll(value, `"`, `\"`)
	return `"` + value + `"`
}
